language: ruby
rvm:
  - 2.7
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-redirect --allow-dupe --white-list github,twitter,softwareengineeringdaily,reddit,linkedin
